"""Report generator — creates downloadable Markdown report from simulation data."""

import json
import logging
from datetime import datetime, timezone

from sqlmodel import Session

from app.database import engine
from app.models.simulation import Simulation, SimulationReport

logger = logging.getLogger(__name__)

REPORT_TEMPLATE = """# Sybil Swarm — Market Prediction Report

**Generated:** {timestamp}
**Product:** {product_name}

---

## Executive Summary

**Market Viability Score: {overall_score:.0f}/100**

- **Conversion Rate:** {conversion_rate:.1f}% of simulated customers would purchase
- **Average Willingness to Pay:** {avg_wtp:.0f}/100
- **Sentiment:** {positive}% positive / {neutral}% neutral / {negative}% negative

---

## Synthesis

{synthesis_narrative}

---

## Top Objections

{objections_section}

## Top Suggestions

{suggestions_section}

---

## Methodology

This report was generated by simulating {total_agents} AI-powered synthetic customer personas
evaluating the product. Each persona has unique demographics, interests, and pain points.
Personas were generated in batches with enforced diversity across age, income, personality type,
and tech-savviness.

- **Bulk agents ({bulk_count}):** Fast evaluation using {bulk_model}
- **Expert agents ({expert_count}):** Deep analysis using {expert_model}
- **Synthesis agent:** Final report generation using {synthesis_model}

---

*Generated by [Sybil Swarm](https://github.com/nghiahsgs/Sybil-Swarm)*
"""


def generate_markdown_report(simulation_id: int) -> str:
    """Generate a Markdown report from simulation results."""
    with Session(engine) as session:
        sim = session.get(Simulation, simulation_id)
        if not sim:
            raise ValueError(f"Simulation {simulation_id} not found")

        report = session.exec(
            __import__("sqlmodel").select(SimulationReport).where(SimulationReport.simulation_id == simulation_id)
        ).first()
        if not report:
            raise ValueError("Report not ready")

        # Parse JSON fields
        sentiment = json.loads(report.sentiment_distribution) if report.sentiment_distribution else {}
        objections = json.loads(report.top_objections) if report.top_objections else []
        suggestions = json.loads(report.top_suggestions) if report.top_suggestions else []

        # Parse product info
        try:
            product_info = json.loads(sim.product_info) if sim.product_info else {}
        except json.JSONDecodeError:
            product_info = {}

        # Format sections
        objections_section = "\n".join(
            f"| {i + 1} | {o.get('objection', 'N/A')} | {o.get('count', 0)} |" for i, o in enumerate(objections[:10])
        )
        if objections_section:
            objections_section = "| # | Objection | Mentions |\n|---|-----------|----------|\n" + objections_section
        else:
            objections_section = "No significant objections reported."

        suggestions_section = "\n".join(
            f"| {i + 1} | {s.get('suggestion', 'N/A')} | {s.get('count', 0)} |" for i, s in enumerate(suggestions[:10])
        )
        if suggestions_section:
            suggestions_section = "| # | Suggestion | Mentions |\n|---|------------|----------|\n" + suggestions_section
        else:
            suggestions_section = "No specific suggestions reported."

        from app.config import settings

        expert_count = settings.expert_agents
        bulk_count = sim.total_agents - expert_count

        return REPORT_TEMPLATE.format(
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            product_name=product_info.get("name", sim.product_input[:80]),
            overall_score=report.overall_score,
            conversion_rate=report.conversion_rate,
            avg_wtp=report.avg_willingness_to_pay,
            positive=sentiment.get("positive", 0),
            neutral=sentiment.get("neutral", 0),
            negative=sentiment.get("negative", 0),
            synthesis_narrative=report.synthesis_narrative or "Synthesis not available.",
            objections_section=objections_section,
            suggestions_section=suggestions_section,
            total_agents=sim.total_agents,
            bulk_count=bulk_count,
            expert_count=expert_count,
            bulk_model=settings.bulk_model,
            expert_model=settings.expert_model,
            synthesis_model=settings.synthesis_model,
        )
